### ISSUE TITLE
Can I use this project for another program?

### ISSUE THREAD

**Issue by HexagonWin** [dogelabshokyu/dogelabshokyu#1]
Hello. This program doesn't have a LICENSE file with it, so I'm unsure if I can use it on my other project/program.
Can I use this on another program that I'm making? Thanks.

**Comment by dogelabshokyu** [comment]
I didn't apply any license at this project.
if you wanna use it, just write su_ky's blog post link.

**Comment by HexagonWin** [comment]
Thanks, issue closing.
